# Generated by Django 5.1.2 on 2024-10-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('dispatch_date', models.DateTimeField()),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('type_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MailApp.mailtype')),
            ],
        ),
    ]
