# Generated by Django 5.1.2 on 2024-10-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
