# Generated by Django 5.1.2 on 2024-10-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0004_mailtype_imap_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.TextField(default='[]'),
        ),
    ]
